"""Converter tests. Each fixture under tests/fixtures/design/*.yaml is
loaded, rendered, and checked against structural invariants.

We deliberately do NOT compare against golden HTML strings — those
break on every cosmetic formatting change and their "expected" values
are themselves generated by the converter, which makes them
tautological. Instead, each fixture asserts the invariants the spec
cares about: responsive prefixing, accessibility attributes, widget
presence, and shape. A future regression in the converter flips one of
these assertions.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
import yaml

from core.tools.builtin.design.html import CanvaUnresolvedError, ir_to_html
from core.tools.builtin.design.html_export import html_export_tool
from core.tools.builtin.design.ir import CanvaAssetSpec, Image, Page
from core.tools.registry import ToolContext

FIXTURES = Path(__file__).parent / "fixtures" / "design"


def _load(name: str) -> Page:
    data = yaml.safe_load((FIXTURES / f"{name}.yaml").read_text())
    return Page.model_validate(data)


def _render(name: str) -> tuple[str, str]:
    bundle = ir_to_html(_load(name))
    return bundle["index.html"], bundle["styles.css"]


# ── Structural invariants (document-wide) ───────────────────────


def test_document_has_doctype_and_viewport() -> None:
    html, _ = _render("hero")
    assert html.startswith("<!DOCTYPE html>")
    assert 'name="viewport"' in html
    assert "tailwindcss.com" in html  # Tailwind CDN script


def test_title_reflects_page_title() -> None:
    html, _ = _render("hero")
    assert "<title>Acme Launch</title>" in html


def test_lang_attribute_applied() -> None:
    html, _ = _render("hero")
    assert '<html lang="en">' in html


def test_styles_css_is_minimal() -> None:
    _, css = _render("hero")
    # Enough to be useful, short enough that big CSS means someone's
    # bypassed the Tailwind-utility convention.
    assert len(css) < 400
    assert "scroll-behavior" in css


# ── Fixture-specific structural assertions ─────────────────────


def test_hero_has_h1_and_two_buttons() -> None:
    html, _ = _render("hero")
    assert "<h1" in html and "Launch better" in html
    assert html.count("<a") == 2  # primary + secondary buttons
    assert "bg-blue-600" in html  # primary
    assert "bg-gray-200" in html  # secondary


def test_hero_responsive_padding_differs_between_mobile_and_desktop() -> None:
    html, _ = _render("hero")
    # Mobile padding is py-[48px] px-[20px], desktop py-[96px] px-[32px].
    assert "py-[48px]" in html
    assert "lg:py-[96px]" in html
    assert "lg:px-[32px]" in html


def test_two_column_mobile_stacks_desktop_row() -> None:
    html, _ = _render("two_column")
    assert "flex-col" in html  # mobile stack
    assert "lg:flex-row" in html  # desktop row


def test_two_column_right_image_has_alt() -> None:
    html, _ = _render("two_column")
    assert 'alt="Illustration of the right side feature"' in html


def test_card_grid_has_three_card_containers() -> None:
    html, _ = _render("card_grid")
    # Three inner containers each with background #ffffff.
    assert html.count("background-color: #ffffff") == 3


def test_nav_has_four_buttons_and_logo_heading() -> None:
    html, _ = _render("nav")
    assert "<h4" in html
    assert html.count("<a ") == 4


def test_nav_justify_between_on_mobile() -> None:
    html, _ = _render("nav")
    assert "justify-between" in html


def test_footer_has_divider_and_dark_background() -> None:
    html, _ = _render("footer")
    assert "background-color: #0f172a" in html
    assert "<hr" in html
    assert "© 2026 Skyway Media" in html


def test_cta_band_center_alignment_and_full_button() -> None:
    html, _ = _render("cta")
    assert "Ready to ship?" in html
    assert 'href="/start"' in html
    # Button variant is primary.
    assert "bg-blue-600" in html


def test_form_fields_render_with_labels_and_required() -> None:
    html, _ = _render("form")
    # 3 fields: full_name, email, message
    assert html.count('class="flex flex-col gap-1">') == 3
    assert 'for="full_name"' in html
    assert 'type="email"' in html
    assert "<textarea" in html
    # Required on all three.
    assert html.count("required") >= 3
    # Submit button.
    assert "Send message" in html


def test_testimonial_quote_text_present_and_center_aligned() -> None:
    html, _ = _render("testimonial")
    assert "PILK cut our landing-page turnaround" in html
    assert "text-center" in html
    # Avatar image alt present.
    assert 'alt="Portrait of Jane Doe, CEO of Example Inc"' in html


def test_feature_list_has_three_icons() -> None:
    html, _ = _render("feature_list")
    assert html.count('data-icon="zap"') == 1
    assert html.count('data-icon="shield"') == 1
    assert html.count('data-icon="sparkles"') == 1


def test_image_text_button_variant_secondary() -> None:
    html, _ = _render("image_text")
    assert "bg-gray-200" in html  # secondary variant
    assert 'alt="Screenshot of the PILK dashboard showing the Approvals tab"' in html


# ── ID + escaping sanity ────────────────────────────────────────


def test_all_ids_unique_across_hero_render() -> None:
    html, _ = _render("hero")
    ids = re.findall(r'\bid="([^"]+)"', html)
    assert len(ids) == len(set(ids)), f"duplicate IDs: {ids}"


def test_escaping_blocks_html_injection() -> None:
    from core.tools.builtin.design.defaults import default_section_settings
    from core.tools.builtin.design.html import ir_to_html
    from core.tools.builtin.design.ir import Container, Heading, Page

    page = Page(
        title="<script>alert(1)</script>",
        slug="x",
        containers=[
            Container(
                settings=default_section_settings(),
                children=[Heading(text="<img onerror=1>", level="h1")],
            )
        ],
    )
    html = ir_to_html(page)["index.html"]
    assert "<script>" not in html
    assert "&lt;script&gt;" in html
    assert "<img onerror" not in html
    assert "&lt;img onerror" in html


# ── CanvaAssetSpec refusal ──────────────────────────────────────


def test_canva_spec_raises_canva_unresolved_error() -> None:
    from core.tools.builtin.design.defaults import default_section_settings
    from core.tools.builtin.design.ir import Container, Page

    page = Page(
        title="t",
        slug="s",
        containers=[
            Container(
                settings=default_section_settings(),
                children=[
                    Image(
                        src=CanvaAssetSpec(
                            query="a pretty hero image", design_type="hero_image"
                        ),
                        alt="alt text",
                    )
                ],
            )
        ],
    )
    with pytest.raises(CanvaUnresolvedError, match="PR I"):
        ir_to_html(page)


# ── Tool wrapper ────────────────────────────────────────────────


@pytest.mark.asyncio
async def test_tool_writes_bundle_to_disk(tmp_path: Path) -> None:
    page_dict = yaml.safe_load((FIXTURES / "hero.yaml").read_text())
    out = await html_export_tool.handler(
        {"ir": page_dict, "output_dir": str(tmp_path / "out")},
        ToolContext(),
    )
    assert not out.is_error
    assert (tmp_path / "out" / "index.html").exists()
    assert (tmp_path / "out" / "styles.css").exists()
    assert out.data["container_count"] == 1
    assert out.data["title"] == "Acme Launch"


@pytest.mark.asyncio
async def test_tool_refuses_missing_ir() -> None:
    out = await html_export_tool.handler(
        {"output_dir": "/tmp/x"}, ToolContext()
    )
    assert out.is_error
    assert "ir" in out.content.lower()


@pytest.mark.asyncio
async def test_tool_refuses_missing_output_dir() -> None:
    out = await html_export_tool.handler(
        {"ir": {"title": "t", "slug": "s", "containers": []}},
        ToolContext(),
    )
    assert out.is_error
    assert "output_dir" in out.content


@pytest.mark.asyncio
async def test_tool_surfaces_validation_errors(tmp_path: Path) -> None:
    bad = {"title": "t", "slug": "s", "containers": [{"settings": {}}]}
    out = await html_export_tool.handler(
        {"ir": bad, "output_dir": str(tmp_path)}, ToolContext()
    )
    assert out.is_error
    assert "invalid IR" in out.content
    assert "errors" in out.data


@pytest.mark.asyncio
async def test_tool_surfaces_canva_unresolved(tmp_path: Path) -> None:
    from core.tools.builtin.design.defaults import default_section_settings

    settings = default_section_settings().model_dump()
    page = {
        "title": "t",
        "slug": "s",
        "containers": [
            {
                "settings": settings,
                "children": [
                    {
                        "widget_type": "image",
                        "src": {
                            "query": "hero lighthouse image",
                            "design_type": "hero_image",
                        },
                        "alt": "alt",
                    }
                ],
            }
        ],
    }
    out = await html_export_tool.handler(
        {"ir": page, "output_dir": str(tmp_path)}, ToolContext()
    )
    assert out.is_error
    assert "PR I" in out.content
