"""IR → static HTML + Tailwind CSS bundle.

Pure function. No filesystem I/O, no LLM, no network. The tool wrapper
(`html_export.py`) is the only side-effecting layer.

Output shape::

    {
        "index.html": "<!DOCTYPE html>... (single HTML doc)",
        "styles.css": "/* minimal reset + any overrides */",
    }

The HTML loads Tailwind via CDN (no build step required downstream)
and expresses every responsive setting through Tailwind's ``md:`` /
``lg:`` prefixes. Breakpoints match Elementor's defaults (768 / 1024)
so a future Elementor converter agent can operate on the same IR
with visual parity.

Arbitrary values — hex colors, odd paddings — are emitted via
Tailwind's bracket syntax (``bg-[#ff5733]``, ``p-[12px]``) rather than
custom CSS. That keeps ``styles.css`` short and diff-friendly.

Design trade-offs worth calling out for review:

* We emit ``md:`` for tablet (≥768px) and ``lg:`` for desktop (≥1024px).
  Mobile is the un-prefixed default. Elementor calls ``lg:`` "desktop"
  and ``md:`` "tablet" too, so the parity holds.
* ``CanvaAssetSpec`` sources raise :class:`CanvaUnresolvedError` —
  PR I adds the resolver; this PR keeps the surface loud rather than
  silently falling back to a placeholder.
"""

from __future__ import annotations

import html as _htmllib
from collections.abc import Callable
from dataclasses import dataclass

from core.tools.builtin.design.ir import (
    Button,
    CanvaAssetSpec,
    Container,
    Divider,
    Form,
    FormField,
    Heading,
    HTMLEmbed,
    Icon,
    Image,
    Page,
    ResponsiveValue,
    Spacer,
    Spacing,
    Text,
    Video,
    Widget,
)


class CanvaUnresolvedError(Exception):
    """Raised when the converter encounters a ``CanvaAssetSpec`` image
    source. PR A does not resolve these; PR I wires the resolver in
    and this exception disappears from the normal code path."""


# ── Public entry point ───────────────────────────────────────────


def ir_to_html(page: Page) -> dict[str, str]:
    """Render a page to the ``{index.html, styles.css}`` bundle."""
    body_fragments: list[str] = []
    for container in page.containers:
        body_fragments.append(_render_container(container, depth=0))

    head = _render_head(page)
    body = "\n".join(body_fragments)
    document = (
        "<!DOCTYPE html>\n"
        f'<html lang="{_esc(page.lang)}">\n'
        f"<head>\n{head}</head>\n"
        f'<body class="antialiased text-gray-900 bg-white">\n'
        f"{body}\n"
        "</body>\n"
        "</html>\n"
    )
    return {"index.html": document, "styles.css": _styles_css()}


# ── Head / styles ────────────────────────────────────────────────


def _render_head(page: Page) -> str:
    return (
        '  <meta charset="utf-8"/>\n'
        '  <meta name="viewport" content="width=device-width, initial-scale=1"/>\n'
        f"  <title>{_esc(page.title)}</title>\n"
        '  <script src="https://cdn.tailwindcss.com"></script>\n'
        '  <link rel="stylesheet" href="styles.css"/>\n'
    )


def _styles_css() -> str:
    # Minimal global styles. Everything layout- and widget-specific
    # lives in Tailwind utility classes.
    return (
        "/* Generated by PILK web_design_agent. */\n"
        "html { scroll-behavior: smooth; }\n"
        "body { font-family: system-ui, -apple-system, 'Segoe UI', sans-serif; }\n"
    )


# ── Container rendering ──────────────────────────────────────────


def _render_container(c: Container, *, depth: int) -> str:
    classes = _container_classes(c)
    style = _container_inline_style(c)
    inner = _render_children(c.children, depth=depth + 1)
    style_attr = f' style="{style}"' if style else ""
    pad = "  " * depth
    return (
        f'{pad}<div id="{_esc(c.id)}" class="{classes}"{style_attr}>\n'
        f"{inner}\n"
        f"{pad}</div>"
    )


def _render_children(children: list[Container | Widget], *, depth: int) -> str:
    out: list[str] = []
    for child in children:
        if isinstance(child, Container):
            out.append(_render_container(child, depth=depth))
        else:
            out.append(_render_widget(child, depth=depth))
    return "\n".join(out)


def _container_classes(c: Container) -> str:
    s = c.settings
    parts: list[str] = ["flex", "w-full"]
    parts += _responsive_flex_direction(s.flex_direction)
    parts += _responsive_gap(s.gap)
    parts += _responsive_align_items(s.align_items)
    parts += _responsive_justify_content(s.justify_content)
    parts += _responsive_padding(s.padding)
    parts += _responsive_margin(s.margin)
    parts += _responsive_max_width(s.max_width)
    # Centre the container box when it has a max-width cap.
    if any(v is not None for v in s.max_width.resolved()):
        parts.append("mx-auto")
    return " ".join(parts)


def _container_inline_style(c: Container) -> str:
    out: list[str] = []
    if c.settings.background_color:
        out.append(f"background-color: {c.settings.background_color}")
    return "; ".join(out)


# ── Responsive helpers ───────────────────────────────────────────
#
# Each helper takes one ResponsiveValue and emits the *minimum* set
# of Tailwind classes needed. If tablet and desktop both inherit from
# mobile, we emit only the unprefixed class. This keeps the class
# list short enough to diff.


def _emit_responsive(
    value: ResponsiveValue,
    render: Callable[[object], str],
) -> list[str]:
    """Emit mobile/tablet/desktop class variants, prefixing every class
    individually. ``render`` may return a space-separated multi-class
    string (e.g. ``"py-[16px] px-[24px]"``); we split and prefix each
    so ``lg:py-[..] lg:px-[..]`` comes out correct."""
    mobile, tablet, desktop = value.resolved()
    out: list[str] = []

    def _cls(prefix: str, raw: str) -> list[str]:
        if not raw:
            return []
        if not prefix:
            return raw.split()
        return [f"{prefix}:{c}" for c in raw.split()]

    out.extend(_cls("", render(mobile)))
    if tablet != mobile:
        out.extend(_cls("md", render(tablet)))
    if desktop != tablet:
        out.extend(_cls("lg", render(desktop)))
    return out


def _responsive_flex_direction(value: ResponsiveValue) -> list[str]:
    mapping = {
        "row": "flex-row",
        "column": "flex-col",
        "row-reverse": "flex-row-reverse",
        "column-reverse": "flex-col-reverse",
    }
    return _emit_responsive(value, lambda v: mapping[v])


def _responsive_gap(value: ResponsiveValue) -> list[str]:
    return _emit_responsive(value, lambda v: f"gap-[{v}px]")


def _responsive_align_items(value: ResponsiveValue) -> list[str]:
    mapping = {
        "start": "items-start",
        "center": "items-center",
        "end": "items-end",
        "stretch": "items-stretch",
    }
    return _emit_responsive(value, lambda v: mapping[v])


def _responsive_justify_content(value: ResponsiveValue) -> list[str]:
    mapping = {
        "start": "justify-start",
        "center": "justify-center",
        "end": "justify-end",
        "between": "justify-between",
        "around": "justify-around",
    }
    return _emit_responsive(value, lambda v: mapping[v])


def _responsive_padding(value: ResponsiveValue) -> list[str]:
    return _emit_responsive(value, _spacing_to_class("p"))


def _responsive_margin(value: ResponsiveValue) -> list[str]:
    return _emit_responsive(value, _spacing_to_class("m"))


def _responsive_max_width(value: ResponsiveValue) -> list[str]:
    def render(v: int | None) -> str:
        return "" if v is None else f"max-w-[{v}px]"

    return _emit_responsive(value, render)


def _spacing_to_class(prefix: str) -> Callable[[Spacing], str]:
    """Emit a compact Tailwind class for a Spacing value.

    Cases handled in rank order:

    * all zero → no class at all (empty string is filtered upstream)
    * all sides equal → ``p-[12px]``
    * y/x symmetric → ``py-[12px] px-[24px]`` joined with a space
    * fully asymmetric → ``pt-[..] pr-[..] pb-[..] pl-[..]``
    """

    def render(s: Spacing) -> str:
        if s.top == s.right == s.bottom == s.left == 0:
            return ""
        if s.top == s.right == s.bottom == s.left:
            return f"{prefix}-[{s.top}px]"
        if s.top == s.bottom and s.left == s.right:
            parts = []
            if s.top != 0:
                parts.append(f"{prefix}y-[{s.top}px]")
            if s.left != 0:
                parts.append(f"{prefix}x-[{s.left}px]")
            return " ".join(parts)
        out: list[str] = []
        if s.top != 0:
            out.append(f"{prefix}t-[{s.top}px]")
        if s.right != 0:
            out.append(f"{prefix}r-[{s.right}px]")
        if s.bottom != 0:
            out.append(f"{prefix}b-[{s.bottom}px]")
        if s.left != 0:
            out.append(f"{prefix}l-[{s.left}px]")
        return " ".join(out)

    return render


# ── Widget rendering ─────────────────────────────────────────────


def _render_widget(w: Widget, *, depth: int) -> str:
    pad = "  " * depth
    match w:
        case Heading():
            return pad + _render_heading(w)
        case Text():
            return pad + _render_text(w)
        case Button():
            return pad + _render_button(w)
        case Image():
            return pad + _render_image(w)
        case Spacer():
            return pad + _render_spacer(w)
        case Divider():
            return pad + _render_divider(w)
        case Icon():
            return pad + _render_icon(w)
        case Form():
            return pad + _render_form(w)
        case Video():
            return pad + _render_video(w)
        case HTMLEmbed():
            return pad + _render_html_embed(w)
    # Shouldn't reach here — the discriminated union covers every case.
    raise TypeError(f"unhandled widget type: {type(w).__name__}")


_HEADING_SIZE = {
    "h1": "text-4xl md:text-5xl lg:text-6xl",
    "h2": "text-3xl md:text-4xl lg:text-5xl",
    "h3": "text-2xl md:text-3xl",
    "h4": "text-xl md:text-2xl",
    "h5": "text-lg md:text-xl",
    "h6": "text-base md:text-lg",
}


def _render_heading(w: Heading) -> str:
    tag = w.level
    classes = [_HEADING_SIZE[w.level], "font-bold", "tracking-tight"]
    if w.align is not None:
        classes += _responsive_text_align(w.align)
    return f'<{tag} id="{_esc(w.id)}" class="{" ".join(classes)}">{_esc(w.text)}</{tag}>'


def _render_text(w: Text) -> str:
    classes = ["text-base", "md:text-lg", "text-gray-700", "leading-relaxed"]
    if w.align is not None:
        classes += _responsive_text_align(w.align)
    return f'<p id="{_esc(w.id)}" class="{" ".join(classes)}">{_esc(w.body)}</p>'


_BUTTON_VARIANT = {
    "primary": (
        "inline-flex items-center justify-center px-6 py-3 rounded-lg "
        "bg-blue-600 text-white font-semibold "
        "hover:bg-blue-700 transition"
    ),
    "secondary": (
        "inline-flex items-center justify-center px-6 py-3 rounded-lg "
        "bg-gray-200 text-gray-900 font-semibold "
        "hover:bg-gray-300 transition"
    ),
    "ghost": (
        "inline-flex items-center justify-center px-6 py-3 rounded-lg "
        "text-blue-600 font-semibold hover:bg-blue-50 transition"
    ),
}


def _render_button(w: Button) -> str:
    target = ' target="_blank" rel="noopener"' if w.open_in_new_tab else ""
    return (
        f'<a id="{_esc(w.id)}" href="{_esc(w.link)}"{target} '
        f'class="{_BUTTON_VARIANT[w.variant]}">{_esc(w.label)}</a>'
    )


def _render_image(w: Image) -> str:
    if isinstance(w.src, CanvaAssetSpec):
        raise CanvaUnresolvedError(
            "Image has a CanvaAssetSpec source but PR A's HTML exporter "
            "cannot resolve it. PR I adds the resolver. Either provide a "
            "URL source now or wait for PR I."
        )
    src_attr = _esc(w.src)
    alt_attr = _esc(w.alt)
    tag = (
        f'<img id="{_esc(w.id)}" src="{src_attr}" alt="{alt_attr}" '
        'class="w-full h-auto rounded-lg" loading="lazy"/>'
    )
    if w.caption:
        return (
            '<figure class="flex flex-col gap-2">\n'
            f"  {tag}\n"
            f'  <figcaption class="text-sm text-gray-500">{_esc(w.caption)}</figcaption>\n'
            "</figure>"
        )
    return tag


def _render_spacer(w: Spacer) -> str:
    cls_parts: list[str] = []
    mobile, tablet, desktop = w.height.resolved()
    cls_parts.append(f"h-[{mobile}px]")
    if tablet != mobile:
        cls_parts.append(f"md:h-[{tablet}px]")
    if desktop != tablet:
        cls_parts.append(f"lg:h-[{desktop}px]")
    return f'<div id="{_esc(w.id)}" class="{" ".join(cls_parts)}" aria-hidden="true"></div>'


def _render_divider(w: Divider) -> str:
    style = f"border-top-width: {w.thickness_px}px; border-color: {w.color}"
    return (
        f'<hr id="{_esc(w.id)}" class="w-full border-0" style="{style}"/>'
    )


def _render_icon(w: Icon) -> str:
    style = f"width: {w.size_px}px; height: {w.size_px}px; color: {w.color}"
    # Inline data- attributes so a future runtime library (Lucide, etc.)
    # can hydrate this into a real SVG. For now we emit an accessible
    # placeholder with the icon name.
    return (
        f'<span id="{_esc(w.id)}" data-icon="{_esc(w.name)}" '
        f'style="{style}" aria-hidden="true" '
        'class="inline-flex items-center justify-center"></span>'
    )


def _render_form(w: Form) -> str:
    field_html = "\n".join(
        "    " + _render_form_field(f) for f in w.fields
    )
    return (
        f'<form id="{_esc(w.id)}" action="{_esc(w.action)}" '
        f'method="{w.method}" class="flex flex-col gap-4">\n'
        f"{field_html}\n"
        f"    <button type=\"submit\" class=\"{_BUTTON_VARIANT['primary']}\">"
        f"{_esc(w.submit_label)}</button>\n"
        "  </form>"
    )


def _render_form_field(f: FormField) -> str:
    label = (
        f'<label for="{_esc(f.name)}" class="text-sm font-medium text-gray-900">'
        f"{_esc(f.label)}</label>"
    )
    required = " required" if f.required else ""
    common = (
        f'id="{_esc(f.name)}" name="{_esc(f.name)}" '
        'class="rounded-lg border border-gray-300 px-3 py-2 '
        'focus:outline-none focus:ring-2 focus:ring-blue-500"'
    )
    if f.type == "textarea":
        control = f'<textarea {common} rows="4"{required}></textarea>'
    else:
        control = f'<input type="{f.type}" {common}{required}/>'
    return (
        '<div class="flex flex-col gap-1">\n'
        f"      {label}\n"
        f"      {control}\n"
        "    </div>"
    )


def _render_video(w: Video) -> str:
    attrs: list[str] = [f'id="{_esc(w.id)}"', f'src="{_esc(w.src)}"']
    if w.controls:
        attrs.append("controls")
    if w.autoplay:
        attrs.append("autoplay")
    if w.muted:
        attrs.append("muted")
    attrs.append('class="w-full rounded-lg"')
    return f'<video {" ".join(attrs)}></video>'


def _render_html_embed(w: HTMLEmbed) -> str:
    # No escaping — HTMLEmbed is the explicit escape hatch.
    return f'<div id="{_esc(w.id)}">\n{w.html}\n</div>'


def _responsive_text_align(value: ResponsiveValue) -> list[str]:
    mapping = {
        "left": "text-left",
        "center": "text-center",
        "right": "text-right",
    }
    return _emit_responsive(value, lambda v: mapping[v])


# ── Escaping ─────────────────────────────────────────────────────


def _esc(s: str) -> str:
    """Minimal HTML escape; quote-safe for attribute values."""
    return _htmllib.escape(str(s), quote=True)


# ── Exposed for tests + callers that want raw access ─────────────


@dataclass(frozen=True)
class _RenderResult:
    """Kept out of the public API — only exists so tests can assert on
    the structural breakdown without re-parsing the rendered HTML."""

    html: str
    css: str


__all__ = ["CanvaUnresolvedError", "ir_to_html"]
